kalo ada kredensial db taro disini ye
String url = "jdbc:mysql://localhost:3306/db_gudang_makmur";
String user = "root"; 
String password = ""; 

menggunakan Xampp mysql

ArtifactId: mysql-connector-j
groupId: com.mysql
version: 9.5.0
type: jar

--query--
CREATE DATABASE db_gudang_makmur;

USE db_gudang_makmur;

-- Tabel untuk Barang
CREATE TABLE barang (
    id VARCHAR(10) PRIMARY KEY,
    nama VARCHAR(100),
    kategori VARCHAR(50),
    stok INT,
    lokasi_rak VARCHAR(20)
);

-- Tabel untuk Supplier
CREATE TABLE supplier (
    id INT AUTO_INCREMENT PRIMARY KEY,
    nama_supplier VARCHAR(100),
    no_telp VARCHAR(15),
    alamat TEXT
);

-- Tabel Transaksi (Relasi)
CREATE TABLE transaksi (
    id INT AUTO_INCREMENT PRIMARY KEY,
    tanggal DATE,
    jenis_transaksi ENUM('Masuk', 'Keluar'),
    jumlah INT,
    id_barang VARCHAR(10),
    FOREIGN KEY (id_barang) REFERENCES barang(id)
);